version: "3.8"
services:
  database:
    image: postgres:15.0-alpine3.16
    restart : always
    expose:
    - "5432"
    ports:
    - "5432:5432"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    command: -p 5432

  python_app:
    build:
      context: ./Python/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - database
    command:
      tail -f /dev/null